name: SneakSound
version: @version@
main: hazae41.minecraft.sneaksound.Plugin
author: hazae41

commands:
  sneaksound:
    aliases: [sneak, farts]
    description: hazae41's SneakSound
    usage: "/<command>"

permissions:
  sneaksound.player:
    default: true
    children:
      sneaksound.use: true
      sneaksound.send: true
      sneaksound.toggle: true
      sneaksound.set: true
      sneaksound.help: true
  sneaksound.admin:
    default: op
    children:
      sneaksound.about: true
      sneaksound.send.other: true
      sneaksound.send.all: true
      sneaksound.list: true
      sneaksound.remake: true
      sneaksound.toggle.other: true
      sneaksound.set.other: true
  sneaksound.*:
    children:
      sneaksound.player: true
      sneaksound.admin: true